---
title: "NCBI - SRA over time"
author: "André Rodrigues Soares"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

initial code from https://gist.github.com/BenLangmead/545634578b6a80e5bba0e31843923e7a

```{r}
library(tidyverse)
```

```{r}
system('curl https://trace.ncbi.nlm.nih.gov/Traces/sra/sra_stat.cgi > stats.csv')
sra = read_csv("stats.csv", 
               col_types = cols(
                 date = col_datetime(format = "%m/%d/%Y"),
                 bases = col_double(),
                 open_access_bases = col_double(),
                 bytes = col_double(),
                 open_access_bytes = col_double())) %>% 
  select(date, bases, bytes) %>% 
  gather("data", "values", -date) %>% 
  mutate(date = as.Date(as.character(date)),
         log_vals = log(values),
         days = as.numeric(difftime(as.Date(date),
                                 min(as.Date(date)),units = "days")))

sra_bases = sra %>% 
  filter(data == "bases")

sra_bytes = sra %>% 
  filter(data == "bytes")
```
## Trends over time

Linear model fitted as from 2017

```{r}
ggplot(sra,
       aes(date, log_vals,
           colour = data, fill = data)) +
  geom_smooth(method = 'lm',
              se = T) +
  theme_bw()

m_bases <- lm(log_vals ~ days, data = sra_bases %>% 
  filter(days > 2000))
summary(m_bases)

model_bases <- nls(values ~ a * exp(b * days),
             data = sra_bases,
             start = list(a = exp(summary(m_bases)$coefficients[1,1]), b = 0.001))
model_bases
summary(model_bases)


m_bytes <- lm(log_vals ~ days, data = sra_bytes %>% 
  filter(days > 2000))
summary(m_bytes)

model_bytes <- nls(values ~ a * exp(b * days),
             data = sra_bytes,
             start = list(a = exp(summary(m_bytes)$coefficients[1,1]), b = 0.001))
model_bytes
summary(model_bytes)

# Predict future values
# Calculate the difference in days between max date and 2030-01-01
days_difference <- as.numeric(difftime(as.Date("2030-01-01"), 
                                       max(sra_bases$date), units = "days"))

# Generate future_time
future_time <- seq(max(sra_bases$days), 
                   max(sra_bases$days) + days_difference, 
                   by = 1)

future_values_bases <- predict(model_bases,
                         newdata = data.frame(days = future_time),  # Corrected variable name
                         interval = "prediction")

future_values_bytes <- predict(model_bytes,
                         newdata = data.frame(days = future_time),  # Corrected variable name
                         interval = "prediction")

future_df = tibble(days = future_time,
                   bases = future_values_bases,
                   bytes = future_values_bytes) %>% 
  mutate(date = min(sra_bases$date) + future_time) %>% 
  pivot_longer(names_to = "data", values_to = "values", -c(days, date)) %>% 
  add_column(type = "prediction")

all_data = bind_rows(sra %>% 
                       add_column(type = "data"),
                     future_df)

ggplot(all_data,
       aes(date, values*0.000000000001,
           colour = data,
           linetype = type)) +
  geom_line() +
  geom_vline(xintercept = as.Date("2024-01-01"),
             linetype = 'dashed', colour = 'grey',
             alpha = .7) +
  scale_x_date(date_breaks = "2 years", 
               date_labels = "%Y") +
  scale_y_continuous(labels = scales::comma_format(),
                     expand = c(0,0)) +
  scale_colour_manual(values = c("#CC6677", "#117733", "#CC6677", "#117733"),
                      labels = c("SRA bases", "SRA bytes", "Predicted SRA bases", "Predicted SRA bytes"),
                        name = "SRA data & predictions") +
  guides(linetype = "none") +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(hjust = 1, vjust = 1, angle = 20),
        legend.position = "bottom") +
  ggtitle("TBytes and Tbases in the NCBI-SRA since 2007",
          subtitle = paste0("Exponential model fitted from data from 2012-11-25 onwards\nLast data point: ", max(sra_bases$date)))
```

```{r}
ggplot(all_data,
       aes(date, values*0.000000000001,
           colour = data,
           linetype = type)) +
  geom_line() +
  geom_vline(xintercept = as.Date("2024-01-01"),
             linetype = 'dashed', colour = 'grey',
             alpha = .7) +
  scale_x_date(date_breaks = "2 years", 
               date_labels = "%Y") +
  scale_y_log10(labels = scales::comma_format(),
                     expand = c(0,0),
                breaks = c(1, 100, 10000, 500000)) +
  scale_colour_manual(values = c("#CC6677", "#117733", "#CC6677", "#117733"),
                      labels = c("SRA bases", "SRA bytes", "Predicted SRA bases", "Predicted SRA bytes"),
                        name = "SRA data & predictions") +
  guides(linetype = "none") +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(hjust = 1, vjust = 1, angle = 20),
        legend.position = "bottom") +
  ggtitle("TBytes and Tbases in the NCBI-SRA since 2007",
          subtitle = paste0("Exponential model fitted from data from 2012-11-25 onwards\nLast data point: ", max(sra_bases$date)))
```

